### ISSUE TITLE
Length limitation for TestItem name and description

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/example-net-specflow#3] opened 2016-12-28 12:07 UTC
Report Portal TestItem cannot be bigger than 256?
TestItem description cannot be bigger than 1042?

Agent should cut string and then send api request.

**Comment by abasau** [comment] 2016-12-28 14:24
I submitted an issue to increase TestItem description length limit months ago. It should be fixed by now but I will need to check what is the current limit.
TestItem name was recently limited to 256 chars.

**Comment by abasau** [comment] 2016-12-30 03:01
Limitation on Description length was removed. Name still has 256 chars limit.

**Comment by abasau** [comment] 2016-12-30 04:11
The issue is addressed in https://github.com/reportportal/client-net/pull/5.

**Closed as completed by abasau** 2016-12-30 04:11 UTC
Labels: bug
